### ISSUE TITLE
Issue in executing End2End

### ISSUE THREAD

**Issue by Shubhneet1805** [zhangmin510/fabric-console#1]
* What operating system are you using?  
Linux
* What version of Node.js is on your system?
v8.11.2

I have successfully build this sample but when it comes to interaction with the fabric console UI i get 

<--------------------------------LOGS---------------------------->
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(electron:3130): dconf-WARNING **: failed to commit changes to dconf: Unknown or unsupported transport 'disabled' for address 'disabled:'

(electron:3130): dconf-WARNING **: failed to commit changes to dconf: Unknown or unsupported transport 'disabled' for address 'disabled:'

(electron:3130): dconf-WARNING **: failed to commit changes to dconf: Unknown or unsupported transport 'disabled' for address 'disabled:'

(electron:3130): dconf-WARNING **: failed to commit changes to dconf: Unknown or unsupported transport 'disabled' for address 'disabled:'
Error creating proxy: Unknown or unsupported transport 'disabled' for address 'disabled:' (g-io-error-quark, 13)
Error creating proxy: Unknown or unsupported transport 'disabled' for address 'disabled:' (g-io-error-quark, 13)
Error creating proxy: Unknown or unsupported transport 'disabled' for address 'disabled:' (g-io-error-quark, 13)
Error creating proxy: Unknown or unsupported transport 'disabled' for address 'disabled:' (g-io-error-quark, 13)
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
<--------------------------------LOGS---------------------------->

Can you specify which all inputs must be given to 
*Connection Profile
*User Management
*Channel management 
*Chaincode Management

**Comment by zhangmin510** [comment]
this project is no longer maintained, thanks for your attention
